Feature/integration tests
M-Anwar-Hussaini/BlogApp pull request #8
Opened 2023-11-14 19:26 UTC by M-Anwar-Hussaini

# New features and changes in this milestone: 
- Solve the (N+1) problem for posts and comments
  - Before `includes` method:

  - ![image](https://github.com/M-Anwar-Hussaini/BlogApp/assets/131291114/eafdcb21-3633-43d3-baf3-9cc5eee880fe)
  - After `inclues` method: 
  - ![image](https://github.com/M-Anwar-Hussaini/BlogApp/assets/131291114/45a35c9e-73ae-48fa-a4b6-7b7d8f5291db)
- Add integration tests for the following views and controllers:
  - `user#index`
  - `user#show`
  - `post#index`
  - `post#show`

2023-11-14 20:18 UTC, Qoosim reviewed
#  *Status: Invalid Request* :red_circle: 

Hi @M-Anwar-Hussaini, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

![](https://user-images.githubusercontent.com/97100091/194103659-a0270409-def7-4972-b884-9f7c141eb90a.gif)

## Invalid Code Review Request

You have submitted a project, that is a pair-programming but contains commits only from on partner. Kindly wait for the reply from student success and attach their email given to you to your PR if you're later allowed to work sole on this milestone.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-11-14 20:32 UTC, Qoosim reviewed
#  *Status: Invalid Request* :red_circle: 

Hi @team, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

![](https://user-images.githubusercontent.com/97100091/194103659-a0270409-def7-4972-b884-9f7c141eb90a.gif)

## Invalid Code Review Request

You have submitted a project, that both partners do not have a fair contribution to the PR. Editing only the readme file is not sufficed to be considered as contributions. Every members must have a fair commit to the PR. 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-11-15 17:01 UTC, frank1738 requested changes
Hi Team, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media2.giphy.com/media/t8YPf3ACKeouLzEIvr/giphy.gif"/>

## Highlights

✅ Solved the `N+1` problem
✅ App is designed as expected 👍 


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

N/A
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-15 17:01 UTC, ghost commented on README.md
>  Contributions, issues, and feature requests are welcome!
- [ ] 🌟 Great work on the documentation! However, there's a tiny hiccup 🚧 - the MIT License link seems to be broken. Let's ensure that there is a License in our repo and be sure to update the URL to keep that professionalism shining! ✨ Keep up the good work! 👏

2023-11-15 17:01 UTC, ghost commented on spec/features/user_show_spec.rb
> +  scenario 'I can see the users name.' do
- [ ] In your `user#show` specs, Kindly add:
   - Tests that redirects to the post's show page when you click on a user's post.

2023-11-15 17:01 UTC, ghost commented on spec/features/post_index_spec.rb
> +    Like.create(user_id: @user.id, post_id: @post1.id)
- [ ] In your `post#index` specs, Kindly add:

     - Tests that asserts you can see how many comments a post has.
     - Tests that asserts you can see how many likes a post has.
     - Tests that asserts you can see a section for pagination if there are more posts than fit on the view.
     - Tests that redirects to the post's show page when you click on a post.

2023-11-15 19:10 UTC, LionRouge1 requested changes
Hi @M-Anwar-Hussaini, 

Great work on making the changes 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![almost](https://media.giphy.com/media/R2m2NzVxQ3pbG/giphy.gif)

## Suggested changes :recycle: 

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-15 19:10 UTC, LionRouge1 commented on spec/features/post_index_spec.rb
- [ ] As mentioned by the previous reviewer there are some test cases that you have not covered. According to the project requirement we should have a test:
   - that asserts how many comments a post has.
   - that asserts  how many likes a post has.
   - that asserts a section for pagination if there are more posts than fit on the view.
 
 Kindly add those tests cases in your `post_index_spec.rb` file to follow the project requirement.
![Screenshot from 2023-11-15 18-57-09](https://github.com/M-Anwar-Hussaini/BlogApp/assets/91142432/1e6a7ebc-78b5-48e2-8a91-f8bdc7800ab0)

2023-11-15 20:32 UTC, cynthiainga approved these changes
Hi @M-Anwar-Hussaini, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![](https://user-images.githubusercontent.com/69011963/151541305-67f4f8e4-c79e-4f9d-a6cf-2c7efc3102c6.gif)

## Highlights

- [ ] All tests are passing ✔️ 
- [ ] All changes are made ✔️ 
- [ ] Correct Gitflow ✔️ 
- [ ] Has `Capybara` gem in `Gemfile` for integration test ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were missed by the previous reviewer and addressing them will really improve your application._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-15 20:35 UTC, merged